Add mdrenderer
lepture/mistune-contrib pull request #1
Opened 2015-06-12 07:15 UTC by perexg

According https://github.com/lepture/mistune/issues/56 , trying to put this extension to mistune-contrib.

2015-06-17 06:35 UTC, lepture commented on mistune_contrib/mdrenderer.py
> +    return '```no-highlight\n' + code + '\n```\n'
why `no-highlight` ?

2015-06-17 06:36 UTC, lepture commented on mistune_contrib/mdrenderer.py
> +"""
doc string should be in rst.

2017-09-06 19:48 UTC, unode commented
Is there any chance this might get merged?
At the moment it seems like none of the python markdown parsers out there can output markdown.

It's a blatantly obvious missing feature despite being requested on almost all of them.

In other words, there's not a single markdown library for python that can parse markdown into some internal representation and re-create markdown from this representation.

2017-09-07 01:40 UTC, lepture commented
ping @perexg

you need to fix things I mentioned.

2017-09-07 06:17 UTC, perexg commented
@lepture : updated, let me know, if you want more changes .

2017-09-07 06:32 UTC, lepture requested changes

2017-09-07 06:32 UTC, lepture commented on mistune_contrib/mdrenderer.py
> +"""
ping @perexg

2017-09-07 06:32 UTC, lepture commented on mistune_contrib/mdrenderer.py
> +class Object:
remove this useless class.

2017-09-07 06:49 UTC, perexg commented
Removed Object class, but I don't see the doc string issue problem. Tried two online RST editors and the result seems fine.

2017-09-07 07:12 UTC, lepture commented
@perexg e.g. https://github.com/lepture/mistune-contrib/blob/master/mistune_contrib/highlight.py

Make your doc string like this.

2017-09-07 07:45 UTC, perexg commented
Done.

2017-09-22 02:08 UTC, merged